// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Terminals.Infrastructure;

#nullable disable

namespace Terminals.Infrastructure.Migrations
{
    [DbContext(typeof(DellinDictionaryDbContext))]
    [Migration("20260421131058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Terminals.Contracts.Entities.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressApartment")
                        .HasColumnType("integer");

                    b.Property<string>("AddressCity")
                        .HasColumnType("text");

                    b.Property<string>("AddressHouseNumber")
                        .HasColumnType("text");

                    b.Property<string>("AddressRegion")
                        .HasColumnType("text");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("text");

                    b.Property<int>("CityCode")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("WorkTime")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.HasKey("Id");

                    b.HasIndex("AddressCity");

                    b.HasIndex("Uuid");

                    b.HasIndex("AddressCity", "AddressRegion");

                    b.ToTable("Office", (string)null);
                });

            modelBuilder.Entity("Terminals.Contracts.Entities.Office", b =>
                {
                    b.OwnsOne("Terminals.Contracts.Entities.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<int>("OfficeId")
                                .HasColumnType("integer");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("OfficeId");

                            b1.ToTable("Office");

                            b1
                                .ToJson("Coordinates")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("OfficeId");
                        });

                    b.OwnsOne("Terminals.Contracts.Entities.Phone", "Phones", b1 =>
                        {
                            b1.Property<int>("OfficeId")
                                .HasColumnType("integer");

                            b1.Property<string>("Additional")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("OfficeId");

                            b1.ToTable("Office");

                            b1
                                .ToJson("Phones")
                                .HasColumnType("jsonb");

                            b1.WithOwner("Office")
                                .HasForeignKey("OfficeId");

                            b1.Navigation("Office");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("Phones")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
